# version: '3.8'

# services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - "8085:80"
#     volumes:
#       - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - node-service

#   node-service:
#     build: ./docker/api
#     ports:
#       - "3000:3000"
#     environment:
#       - DB_HOST=${DB_HOST}
#       - DB_USERNAME=${DB_USERNAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_DATABASE=${DB_DATABASE}
#     depends_on:
#       - db


#   # db:
#   #   image: mariadb:latest
#   #   restart: always
#   #   environment:
#   #     MARIADB_ROOT_PASSWORD: password

#   # adminer:
#   #   image: adminer
#   #   restart: always
#   #   ports:
#   #     - 8080:8080

#   db:

#     image: mariadb:latest
#     container_name: dockerDB
#     environment:
#         - MARIADB_ROOT_PASSWORD:password
#     #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#     #   - MYSQL_DATABASE=${MYSQL_DATABASE}
#     #   - MYSQL_USER=${MYSQL_USER}
#     #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#     volumes:
#       - db_data:/var/lib/mysql
    
    

# volumes:
#   db_data:


version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

  node-service:
    build: ./docker/api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: testdb
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: dockerDB
    environment:
      MARIADB_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
