version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

  node-service:
    build: ./docker/api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: dockerChallenge
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: dockerDB
    environment:
      MARIADB_ROOT_PASSWORD: password
      MYSQL_DATABASE: dockerChallenge
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
