version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

  node-service:
    build: ./docker/api
    ports:
      - "3000:3000"
    
    environment:
       DB_HOST: ${DBHOST}
       DB_USERNAME: ${DBUSERNAME}
       DB_PASSWORD: ${DBPASSWORD}
       DB_DATABASE: ${DBDATABASE}
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: dockerDB
    environment:
      
      MARIADB_ROOT_PASSWORD: ${MARIADBROOTPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}




    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
