version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8087:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

  node-service:
    image: my_node_service_image:latest
    ports:
      - "3000"
    environment:
      DB_HOST: ${DBHOST}
      DB_USERNAME: ${DBUSERNAME}
      DB_PASSWORD: ${DBPASSWORD}
      DB_DATABASE: ${DBDATABASE}
    deploy:
      replicas: 3
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADBROOTPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

